### ISSUE TITLE
environment variables not updating

### ISSUE THREAD

**Issue by aliatsis** [HyperBrain/serverless-aws-alias#91]
Hi, I've been using this plugin without any issues so far. However, I just noticed that any new or modified environment variables I place in my serverless.yml are not being deployed to the lambda console and thus are not available to my function.

I've modified both resources and function code to attempt to fix it, but the env vars remain as the initially deployed set even though a new function version has been deployed.

I'm not entirely sure if this issue is a bug/feature of this plugin or if it should be filed with the framework itself. Any help and guidance you can provide would be much appreciated.

**Comment by HyperBrain** [comment]
Hi @aliatsis ,

the environment variables are set by the framework (in the lambda function resource) and the version is also created by SLS to persist the vars. The plugin does not do anything else than moving the version resource to the alias stack, so it does not even have any knowledge about the function configuration.

Did you use version 1.25 of the framework? Previous Serverless versions had a severe bug in the version handling, that never updated any versions, because SLS did not create a new version on config changes.

**Comment by aliatsis** [comment]
thanks so much @HyperBrain ! Interestingly, I am using 1.25. I guess I'll have to move this over to the framework's issues.
