### ISSUE TITLE
Deploying an alias with authorizers overwrites dev alias.

### ISSUE THREAD

**Issue by crobot83** [HyperBrain/serverless-aws-alias#96]
Example:
Deploy a "newAlias" with an existing "dev" alias. The Authorizers of type "REQUEST" will overwrite the existing "dev" alias authorizers. 

Appending a stage variable as a suffix to the lambda for authorizer should fix the situation.

Workaround appears to be going into API Gateway -> Instance -> Authorizers -> Edit authorizer and save.

**Comment by HyperBrain** [comment]
@crobot83 Thanks for reporting.

Do you mean, that the function itself gets overwritten or the authorizer definition in the APIG?
Or is the workaround to just add the alias name to the target lambda name (like my-auth-lambda:${SERVERLESS_ALIAS}) ?

Please explain it in more detail, so that it is clear what exactly happens.

**Comment by zachboyd** [comment]
Based on the description above, I think the core issue is that authorizers of type **REQUEST** do not have the stage variable appended. 

i.e

REQUEST type authorizer -> my-custom-lambda
TOKEN type authorizer -> my-custom-lambda:${stageVariables.SERVERLESS_ALIAS}

I have also seen an issue where you do have to "Edit" and then "Save" the **REQUEST** type authorizers within AWS console so that they function correctly. However, this may be unrelated issue to this particular one.

**Comment by HyperBrain** [comment]
Thanks, yes that makes sense. I agree that the handling should be the same.

**Comment by crobot83** [comment]
Sorry for my lack of clarity, @zachboyd is correct.

**Comment by HyperBrain** [comment]
Released with 1.6.0
